version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://root:root@db:5432/db
      CLIENT_URL: http://localhost:5173
      JWT_SECRET: qdwH23rvrvww3r4r3
      JWT_EXP: 1d
      MAIL_HOST: smtp.gmail.com
      MAIL_USER: fakeroot94@gmail.com
      MAIL_PASSWORD: memm cchg tscz gioi
      MAIL_FROM: fakeroot94@gmail.com
    depends_on:
      - db

volumes:
  pgdata:
